development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["FLY_REGION"] == ENV["PRIMARY_REGION"] ? ENV["REDIS_URL"] : ENV["REDIS_REPLICA_URL"] %>
  channel_prefix: hotwire_counter_production
